version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - redis_network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    networks:
      - redis_network
    depends_on:
      - redis

volumes:
  redis_data:
  redisinsight_data:

networks:
  redis_network:
    driver: bridge
